# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
#
#

#development:
#  PUSHER_APP_ID: "1119298"
#  PUSHER_KEY: "c1c5cb076e25349e91f6"
#  PUSHER_SECRET: "1132a15252d752cdc4cf"
#  PUSHER_CLUSTER: "mt1"

#testing:
#  PUSHER_APP_ID: "1119298"
#  PUSHER_KEY: "c1c5cb076e25349e91f6"
#  PUSHER_SECRET: "1132a15252d752cdc4cf"
#  PUSHER_CLUSTER: "mt1"

#production:
#  PUSHER_APP_ID: "1119297"
#  PUSHER_KEY: "2361ec2ae8ef558636d8"
#  PUSHER_SECRET: "4ba278a6ee9aa13fe3dc"
#  PUSHER_CLUSTER: "mt1"